### ISSUE TITLE
Destroying a socket with outstanding asynchronous operations leaks memory.

### ISSUE THREAD

**Issue by JenSte** [zeromq/azmq#143]
When a socket is destroyed while an async operation is outstanding, leak sanitizer finds a memory leak. The following example program ...
```
#include <azmq/socket.hpp>
#include <boost/asio.hpp>
#include <memory>
#include <iostream>

int main()
{
    int major, minor, patch;
    zmq_version(&major, &minor, &patch);

    std::cout << "boost version: " << BOOST_LIB_VERSION << '\n'
              << "zmq version: " << major << '.' << minor << '.' << patch << '\n'
              << "azmq version: git-a8f54cc8\n"
              << "gcc version: " << __GNUC__ << '.' << __GNUC_MINOR__ << '.' << __GNUC_PATCHLEVEL__ << std::endl;

    boost::asio::io_service io;

    std::unique_ptr<azmq::pair_socket> socket =
        std::make_unique<azmq::pair_socket>(io);
    socket->bind("tcp://0.0.0.0:*");
    socket->async_receive(
        [](
            const boost::system::error_code& ec,
            azmq::message& msg,
            size_t bytes_transferred)
        {
            std::cout << "async_receive_handler" << std::endl;
            if (ec)
                std::cout << "error: " << ec << std::endl;
        });

    boost::asio::signal_set signals(io, SIGINT);
    signals.async_wait(
        [&socket](
            const boost::system::error_code& ec,
            int signal_number)
        {
            std::cout << "signals.async_wait handler" << std::endl;
            if (ec) {
                std::cout << "error: " << ec << std::endl;
                return;
            }

            // Uncommenting the following lines eleminates the leak.
            // socket->cancel();
            socket.reset();
        });

    io.run();
}
```
... yields this output:
```
boost version: 1_63
zmq version: 4.1.6
azmq version: git-a8f54cc8
gcc version: 7.3.1
^Csignals.async_wait handler

=================================================================
==20938==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f2022532158 in operator new(unsigned long) (/lib64/libasan.so.4+0xe0158)
    #1 0x453768 in enqueue<azmq::detail::receive_op<main()::<lambda(const boost::system::error_code&, azmq::message&, size_t)> >, main()::<lambda(const boost::system::error_code&, azmq::message&, size_t)>, int&> /home/jens/azmq-leak/azmq/azmq/detail/socket_service.hpp:460
    #2 0x4535bd in async_receive<main()::<lambda(const boost::system::error_code&, azmq::message&, size_t)> > /home/jens/azmq-leak/azmq/azmq/socket.hpp:565
    #3 0x4532b8 in main /home/jens/azmq-leak/main.cpp:21
    #4 0x7f2020e47889 in __libc_start_main (/lib64/libc.so.6+0x20889)

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 1 allocation(s).
```
When the `socket->cancel();` is uncommented, the leak does not happen.

The CMake file to build the executable:
```
cmake_minimum_required(VERSION 3.2)
project(leak)

find_package(Threads
    REQUIRED
)

find_package(Boost 1.60
  REQUIRED COMPONENTS
  regex
  system
)

find_package(PkgConfig)
pkg_search_module(LIBZMQ REQUIRED libzmq)

add_executable(leak
  main.cpp
)

target_compile_options(leak
  PRIVATE
  -fsanitize=address
)

target_include_directories(leak
  PUBLIC
  ${Boost_INCLUDE_DIR}
  ${ZEROMQ_INCLUDE_DIRS}
  azmq/
)

target_link_libraries(leak
  PUBLIC
  ${Boost_SYSTEM_LIBRARY}
  ${Boost_REGEX_LIBRARY}
  ${LIBZMQ_LIBRARIES}
  Threads::Threads
  -fsanitize=address
)
```

**Comment by aboseley** [comment]
closed by #167
